version: 2.1
orbs:
  python: circleci/python@2
jobs:
  build:
    docker:
      - image: cimg/python:3.8-node
    steps:
      - checkout
      - run:
          name: install required files
          command: |
            python -m venv division
            . division/bin/activate
            pip install -r requirements.txt
      - run:
          name: run test
          command: |
            . division/bin/activate
            python -m pytest tests -v --cov
      - store_test_results:
          path: junit.xml
workflows:
  build-and-test:
    jobs:
      - build